server:
    port: 5335
    
    # Allow all private networks inbound
    access-control: 127.0.0.0/8 allow
    access-control: 10.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow
    access-control: 192.168.0.0/16 allow

    hide-identity: yes
    hide-version: yes

    module-config: "respip validator iterator"
    
    trust-anchor-file: /var/lib/unbound/root.key

# ALLOWLIST — First RPZ, Used to allow domains before they get to the blocklist "hagezi" RPZ(if they exist there). Good for exemption.
rpz:
    name: "allowlist"
    zonefile: "/etc/unbound/responsepolicyzone/allowlist-rpz.txt"

# Custom RPZ for my homelab. Such as some A Record "somedomain.homelab" that points to 172.16.0.2
rpz:
    name: "homelab"
    zonefile: "/etc/unbound/responsepolicyzone/homelab-rpz.txt"

# BLOCKLIST - this list should be frequently updated via update-hagezi-blocklist.sh script
rpz:
    name: "hagezi"
    zonefile: "/etc/unbound/responsepolicyzone/hagezi-rpz.txt"